name: Deploy Python App to Azure VM

on:
  push:
    branches:
      - master  # غيّر هذا لو عندك فرع مختلف

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. Set up SSH key
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 5. Copy update script to Azure VM
      - name: Copy update script to Azure VM
        run: |
          scp -o StrictHostKeyChecking=no ./update_app.sh azureuser@${{ secrets.VM_IP }}:/home/azureuser/update_app.sh

      # 6. Make the script executable
      - name: Make update script executable
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_IP }} "chmod +x /home/azureuser/update_app.sh"

      # 7. Run the script on the VM
      - name: Run update script on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_IP }} "bash /home/azureuser/update_app.sh"
